version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  echo:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Checkout source code
          command: dir
#       - run:
#           name: 'Run the legacy Collection Partner Docker container'
#           command: |
#             Start-Process powershell -Verb runAs
#             docker run --name legacy-build -v C:\Users\circleci\project\levolu:C:\levolu collectionpartnersolutions/legacy dir
            


workflows:
  main:
    jobs:
      - echo
