version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  echo:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Checkout source code
          command: dir
      - run:
          name: Check Docker details
          command: |
            docker --version
            docker volume ls
      - run:
          name: 'Run the legacy Collection Partner Docker container'
          command: |
            # docker run --name legacy-build -v C:\Users\circleci\project:C:\Source collectionpartnersolutions/legacy dir
            # No volume mounting
            docker run --name legacy-build collectionpartnersolutions/legacy dir
            


workflows:
  main:
    jobs:
      - echo
