version: 2.1

jobs:
  echo:
    docker:
      - image: cloudfoundry/windows2016fs:2019
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout:
          path: C:\source
      - run:
          command: |
              tree C:\source

workflows:
  main:
    jobs:
      - echo
